-- Maruti Suzuki Sales Performance Analysis
-- Tools: SQL, PostgreSQL
-- Dataset: Maruti Suzuki sales data from 2020 to 2024


-- Create the main sales table

CREATE TABLE maruti_sales (
    month VARCHAR(7),
    car_model VARCHAR(100),
    segment VARCHAR(50),
    fuel_type VARCHAR(50),
    transmission VARCHAR(50),
    ex_showroom_price_lakh DECIMAL(10,2),
    units_sold DECIMAL(10,2),
    revenue_crores DECIMAL(12,2),
    mileage_kmpl DECIMAL(10,2),
    customer_rating DECIMAL(3,2),
    annual_service_cost_inr DECIMAL(12,2),
    safety_rating_stars DECIMAL(3,2)
);


-- View the imported data

SELECT * FROM maruti_sales;


-- Q1: Calculate the overall sales performance
-- Find total units sold and total revenue generated.

SELECT
    SUM(units_sold) AS total_units_sold,
    SUM(revenue_crores) AS total_revenue_crores
FROM maruti_sales;


-- Q2: Identify the top-selling Maruti Suzuki car models
-- Calculate total units sold for each car model.

SELECT
    car_model,
    SUM(units_sold) AS total_units_sold
FROM maruti_sales
GROUP BY car_model
ORDER BY total_units_sold DESC;


-- Q3: Identify the top revenue-generating Maruti Suzuki models
-- Calculate total revenue generated by each model.

SELECT
    car_model,
    SUM(revenue_crores) AS total_revenue_crores
FROM maruti_sales
GROUP BY car_model
ORDER BY total_revenue_crores DESC;


-- Q4: Analyze sales and revenue by vehicle segment

SELECT
    segment,
    SUM(units_sold) AS total_units_sold,
    SUM(revenue_crores) AS total_revenue_crores
FROM maruti_sales
GROUP BY segment
ORDER BY total_units_sold DESC;


-- Q5: Analyze yearly sales performance
-- Calculate total units sold for each year.

SELECT
    LEFT(month, 4) AS sales_year,
    SUM(units_sold) AS total_units_sold
FROM maruti_sales
GROUP BY LEFT(month, 4)
ORDER BY sales_year;


-- Q6: Find total sales of each model by year

SELECT
    LEFT(month, 4) AS year,
    car_model,
    SUM(units_sold) AS total_units_sold
FROM maruti_sales
GROUP BY
    LEFT(month, 4),
    car_model
ORDER BY
    year,
    total_units_sold DESC;


-- Q7: Analyze sales and revenue by fuel type

SELECT
    fuel_type,
    SUM(units_sold) AS total_units_sold,
    SUM(revenue_crores) AS total_revenue_crores
FROM maruti_sales
GROUP BY fuel_type
ORDER BY total_units_sold DESC;


-- Q8: Analyze sales and revenue by transmission type

SELECT
    transmission,
    SUM(units_sold) AS total_units_sold,
    SUM(revenue_crores) AS total_revenue_crores
FROM maruti_sales
GROUP BY transmission
ORDER BY total_units_sold DESC;


-- Q9: Compare total sales and revenue by car model

SELECT
    car_model,
    SUM(units_sold) AS total_units_sold,
    SUM(revenue_crores) AS total_revenue_crores
FROM maruti_sales
GROUP BY car_model
ORDER BY total_units_sold DESC;


-- Q10: Compare customer ratings across car models

SELECT
    car_model,
    AVG(customer_rating) AS average_rating
FROM maruti_sales
GROUP BY car_model
ORDER BY average_rating DESC;


-- Q11: Compare mileage and total sales by car model

SELECT
    car_model,
    AVG(mileage_kmpl) AS average_mileage,
    SUM(units_sold) AS total_units_sold
FROM maruti_sales
GROUP BY car_model
ORDER BY total_units_sold DESC;


-- Q12: Compare sales across different safety-rating levels

SELECT
    safety_rating_stars,
    SUM(units_sold) AS total_units_sold,
    SUM(revenue_crores) AS total_revenue_crores
FROM maruti_sales
GROUP BY safety_rating_stars
ORDER BY total_units_sold DESC;


-- Q13: Rank car models based on total revenue

SELECT
    car_model,
    SUM(revenue_crores) AS total_revenue_crores,
    RANK() OVER (ORDER BY SUM(revenue_crores) DESC) AS revenue_rank
FROM maruti_sales
GROUP BY car_model
ORDER BY revenue_rank;


-- Q14: Analyze monthly sales performance

SELECT
    month,
    SUM(units_sold) AS total_units_sold
FROM maruti_sales
GROUP BY month
ORDER BY total_units_sold DESC;
